### ISSUE TITLE
Add to FreeCAD-Addons repo

### ISSUE THREAD

**Issue by luzpaz** [HakanSeven12/FreeCAD-Geomatics-Workbench#2]
@HakanSeven12 when you're ready (even if it's just to beta test) you can open ticket at https://github.com/FreeCAD/FreeCAD-Addons to have this fine workbench be added to the repo so testers can easily help you test it and potentially improve it together with you.

**Comment by HakanSeven12** [comment]
When WB is ready I will do it :)

**Comment by luzpaz** [comment]
Hey @yorikvanhavre can you give the green light for adding this workbench to the Addon Manager ? @HakanSeven12 says it's ready although not complete. Is it possible for us to have a 'Status: Beta' that is prominent in the AddonManager UI? (obviously, besides adding that in bold to the WB README.md which is a workaround solution in the meantime)

**Comment by luzpaz** [comment]
Maybe we should post something on the forum thread to get his attention?

**Comment by yorikvanhavre** [comment]
Sorry guys, I'm a bit full of stuff, can't process as fast as I want :) 
What's the url of this addon?

**Comment by yorikvanhavre** [comment]
Added https://github.com/FreeCAD/FreeCAD-addons/commit/d2e0709fa54cd893aaafcf26b7491c973e850fe9

**Comment by HakanSeven12** [comment]
Thanks guys :)
