### ISSUE TITLE
License is missing from repo + license header missing in source code 

### ISSUE THREAD

**Issue by luzpaz** [HakanSeven12/FreeCAD-Geomatics-Workbench#4]

**Comment by HakanSeven12** [comment]
I think you talking about this https://github.com/HakanSeven12/FreeCAD-Geomatics-Workbench/blob/master/Init.py

**Comment by HakanSeven12** [comment]
I think you are talking about this https://github.com/HakanSeven12/FreeCAD-Geomatics-Workbench/blob/master/LICENSE

**Comment by HakanSeven12** [comment]
I added license to project. If nothing else, I will close this issue.
